const gatherings = [
	"Rock Concert",
	"Symposium",
	"Choir",
	"Rehearsal",
	"Wedding",
	"Birthday Party",
	"Graduation Ceremony",
	"Funeral",
	"Protest",
	"Parade",
	"Festival",
	"Conference",
	"Convention",
	"Exhibition",
	"Rally",
	"Seminar",
	"Workshop",
	"Meeting",
	"Summit",
	"Gathering",
	"Assembly",
	"Rave",
	"Mardi Gras",
	"Carnival",
	"Fair",
	"Market",
	"Trade Show",
	"Competition",
	"Tournament",
	"Match",
	"Game Night",
	"Movie Night",
	"Music Festival",
	"Art Gallery Opening",
	"Book Club",
	"Debate",
	"Panel Discussion",
	"Networking Event",
	"Job Fair",
	"Open Mic Night",
	"Karaoke Night",
	"Poetry Slam",
	"Quiz Night",
	"Speed Dating",
	"Hackathon",
	"Startup Weekend",
	"Hackerspace",
	"Maker Faire",
	"LAN Party",
	"LAN Gaming Tournament",
	"Cooking Class",
	"Wine Tasting",
	"Beer Festival",
	"Craft Fair",
	"Fashion Show",
	"Tech Conference",
	"Comic Con",
	"Anime Convention",
	"Fan Expo",
	"Gaming Convention",
	"Science Fair",
	"History Fair",
	"Art Fair",
	"Film Festival",
	"Food Truck Festival",
	"Outdoor Concert",
	"Indoor Concert",
	"Gallery Opening",
	"Fashion Week",
	"Trade Fair",
	"Music Recital",
	"Dance Recital",
	"Theater Performance",
	"Opera",
	"Ballet",
	"Circus",
	"Magic Show",
	"Stand-up Comedy Show",
	"Improvisation Show",
	"Spelling Bee",
	"Science Olympiad",
	"Robotics Competition",
	"Math Competition",
	"Chess Tournament",
	"Bridge Tournament",
	"Darts Tournament",
	"Ping Pong Tournament",
	"Board Game Night",
	"Film Screening",
	"Art Workshop",
	"Photography Workshop",
	"Yoga Retreat",
	"Meditation Retreat",
	"Wellness Retreat",
	"Spiritual Retreat",
	"Writing Retreat",
	"Camping Trip",
	"Hiking Trip",
	"Road Trip",
	"Backpacking Trip",
	"Ski Trip",
	"Snowboarding Trip",
	"Beach Party",
	"Pool Party",
	"BBQ",
	"Picnic",
	"Bonfire",
	"Campfire",
	"Outdoor Wedding",
	"Indoor Wedding",
	"Reception",
	"Banquet",
	// Add more gatherings as needed
];

export default gatherings;
