const professions = [
	"Doctors",
	"Lawyers",
	"Teachers",
	"Engineers",
	"Scientists",
	"Artists",
	"Writers",
	"Designers",
	"Architects",
	"Chefs",
	"Actors",
	"Musicians",
	"Athletes",
	"Farmers",
	"Pilots",
	"Firefighters",
	"Police Officers",
	"Soldiers",
	"Sailors",
	"Dentists",
	"Nurses",
	"Veterinarians",
	"Pharmacists",
	"Mechanics",
	"Plumbers",
	"Electricians",
	"Carpenters",
	"Welders",
	"Painters",
	"Decorators",
	"Cashiers",
	"Waiters",
	"Bartenders",
	"Cleaners",
	"Janitors",
	"Security Guards",
	"Professors",
	"Librarians",
	"Researchers",
	"Analysts",
	"Managers",
	"Directors",
	"CEOs",
	"Entrepreneurs",
	"Investors",
	"Accountants",
	"Bankers",
	"Economists",
	"Financial Advisors",
	"Insurance Agents",
	"Real Estate Agents",
	"Brokers",
	"Travel Agents",
	"Tour Guides",
	"Interpreters",
	"Translators",
	"Journalists",
	"Reporters",
	"Photographers",
	"Videographers",
	"Animators",
	"Illustrators",
	"Sculptors",
	"Potters",
	"Jewelers",
	"Tailors",
	"Dressmakers",
	"Models",
	"Cooks",
	"Bakers",
	"Butchers",
	"Fishermen",
	"Hunters",
	// Add more professions as needed
];

export default professions;
