const vehicles = [
	"cars",
	"trucks",
	"bicycles",
	"motorcycles",
	"buses",
	"vans",
	"scooters",
	"ambulances",
	"fire trucks",
	"police cars",
	"taxis",
	"limousines",
	"garbage trucks",
	"delivery trucks",
	"pickup trucks",
	"school buses",
	"subway trains",
	"cargo ships",
	"yachts",
	"sailboats",
	"cruise ships",
	"jets",
	"helicopters",
	"airplanes",
	"gliders",
	"hot air balloons",
	"blimps",
	"rockets",
	"space shuttles",
	"satellites",
	"hovercrafts",
	"segways",
	"skateboards",
	"rollerskates",
	"scooters",
	"unicycles",
	"monster trucks",
	"tractor-trailers",
	"dump trucks",
	"tow trucks",
	"ice cream trucks",
	"garbage trucks",
	"mail trucks",
	"food trucks",
	"ambulances",
	"police cars",
	"fire trucks",
	"construction vehicles",
	"snowplows",
	"bulldozers",
	"excavators",
	"cranes",
	"forklifts",
	"tractors",
	"backhoes",
	"dump trucks",
	"cement mixers",
	"graders",
	"road rollers",
	"street sweepers",
	"diggers",
	"payloaders",
	"skid steer loaders",
	"boom trucks",
	"bucket trucks",
	"streetcars",
	"tramways",
	"trolleys",
	"horse-drawn carriages",
	"rickshaws",
	"gondolas",
	"funiculars",
	"cable cars",
	"ski lifts",
	"chairlifts",
	"gondola lifts",
	"escalators",
	"elevators",
	"moving sidewalks",
	"mechanical stairs",
	"conveyor belts",
	"pedestrian bridges",
	"footbridges",
	"bike paths",
	"skate parks",
	"racing tracks",
	"carousels",
	"ferris wheels",
	"roller coasters",
	"bumper cars",
	"go-karts",
	"water slides",
	"swings",
	"slides",
	"monkey bars",
	"jungle gyms",
	"seesaws",
];

export default vehicles;
